spring.application.name=gatewayserver

spring.config.import=optional:configserver:http://localhost:8085

management.endpoints.web.exposure.include=*

info.app.name= Gateway Server microservice
info.app.description= This microservice is responsible for managing gateway in microservices
info.app.version= 1.0.0
management.info.env.enabled=true

spring.cloud.gateway.discovery.locator.enabled=true