spring.application.name=gatewayserver

spring.config.import=optional:configserver:http://localhost:8085

# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#management.endpoint.gateway.enabled=true
#management.endpoint.gateway.access=read-only
management.endpoint.gateway.access=unrestricted

# Info endpoints
info.app.name= Gateway Server microservice
info.app.description= This microservice is responsible for managing gateway in microservices
info.app.version= 1.0.0
management.info.env.enabled=true

# Gateway configuration
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Eureka configuration
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8065/eureka/


