spring.datasource.url=jdbc:h2:mem:bookingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

spring.application.name=hotels
spring.profiles.active=dev
spring.config.import=optional:configserver:http://localhost:8085

eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8065/eureka/

management.endpoints.web.exposure.include=*

info.app.name= Hotels microservice
info.app.description= This microservice is responsible for managing hotels in the booking system
info.app.version= 1.0.0

management.info.env.enabled=true
endpoint.shutdown.enabled=true
management.endpoint.shutdown.enabled=true

#Ciruit braker configuration
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.searchHotelByIdSupportCB.minimumNumberOfCalls=7
resilience4j.circuitbreaker.instances.searchHotelByIdSupportCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.searchHotelByIdSupportCB.waitDurationInOpenState=20000
resilience4j.circuitbreaker.instances.searchHotelByIdSupportCB.permittedNumberOfCallsInHalfOpenState=3

#retry pattern configuration
resilience4j.retry.instances.searchHotelByIdSupportRetry.maxAttempts=3
resilience4j.retry.instances.searchHotelByIdSupportRetry.waitDuration=1500
resilience4j.retry.instances.searchHotelByIdSupportRetry.retryExceptions=feign.FeignException,java.io.IOException,java.net.SocketException

#Logging configuration for resilience4j
logging.level.io.github.resilience4j=DEBUG
logging.level.io.github.resilience4j.retry=DEBUG
logging.level.io.github.resilience4j.retry.event=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG


